name: rag-evaluation-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi>=0.109.0
      - pydantic>=2.6.0
      - python-dotenv>=1.0.0
      - openai>=1.10.0
      - azure-identity>=1.15.0
      - qdrant-client>=1.7.0
      - tiktoken>=0.5.2
      - sentence-transformers>=2.2.2
      - ragas>=0.0.22
      - datasets>=2.16.1
      - azure-ai-ml>=1.12.0
      - mlflow>=2.9.0
